##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.dotnetcore_runtime31:3.1.3 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT="/conteco/bin/dotnetcore_runtime22/entrypoint"
WORKDIR /app
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="dotnetcore_runtime22" \
    CONTECO_NAME="base" \
    CONTECO_TAG="3.1.3" \
    CONTECO_BASE="external.dotnetcore_runtime31:3.1.3" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="dotnetcore_runtime22" \
      io.vcweb.name="base" \
      io.vcweb.tag="3.1.3" \
      io.vcweb.base="external.dotnetcore_runtime31:3.1.3" \
      io.vcweb.build="image-base" \
      io.vcweb.label="dotnetcore_runtime31.base - Conteco" \
      io.vcweb.description="Microsoft dotnetcore runtime 3.1 image for the ContEco ecosystem." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.dotnetcore_runtime22.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
