---
version: '3'
services:

# START SERVICE dotnetcore_runtime31.base
  dotnetcore_runtime31:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.dotnetcore_runtime31.base:3.1.3
    environment: [${CONTECO_DC_DOTNETCORE_RUNTIME31_ENVIRONMENT}]
    command: [${CONTECO_DC_DOTNETCORE_RUNTIME31_COMMAND}]
    volumes: ['${CONTECO_STACKPREFIX}_dotnetcore_RUNTIME31_volume:/app']
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${CONTECO_DC_DOTNETCORE_RUNTIME31_DEPLOY_MODE}
      resources:
        limits:
          cpus: '${CONTECO_DC_DOTNETCORE_RUNTIME31_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_DOTNETCORE_RUNTIME31_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_DOTNETCORE_RUNTIME31_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_DOTNETCORE_RUNTIME31_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_DOTNETCORE_RUNTIME31_DEPLOY_PLACEMENT_CONSTRAINTS}]
      ${CONTECO_DC_BASH_DEPLOY_EXTENSIONS}
    ${CONTECO_DC_BASH_SERVICE_EXTENSIONS}
# END SERVICE dotnetcore_runtime31.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_dotnetcore_RUNTIME31_volume: { external: true }}
${CONTECO_DC_BASH_GLOBAL_EXTENSIONS}
